export default {
  home: '/',
  phoneLogin: '/phone-login',
  verifyPhone: '/verify-phone',
  emailSignUp: '/email-signup',
  emailSignIn: '/email-signin',
  verifyEmail: '/verify-email',
  forgetPassword: '/forget-password',
  socialLogin: '/social-login',
  trips: '/trips',
  ride: '/ride',
  chat: '/chat',
  editAccount: '/edit-account',
  settings: '/settings',
  places: '/places',
  history: '/history',
  addPlace: '/add-place',
  findAddress: '/find-address',
};
